"use client"
import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { useParams } from "next/navigation"
import { useAuth } from "@/contexts/AuthContext"
import { assetUrl, fetchConnections, fetchProjects, fetchUserById, recordProfileView, requestConnection } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Code2, MapPin, Calendar, Github, Linkedin, Globe, Twitter, Briefcase, UserPlus, UserCheck, Clock3, MessageSquare } from "lucide-react"
import { formatLocalDateTime } from "@/lib/time"
import { ThemeToggle } from "@/components/theme-toggle"

type AuthUserLike={id?:string;_id?:string}
const safeUrl=(v?:string)=>{const r=String(v||"").trim();if(!r)return"";const u=r.startsWith("http")?r:`https://${r}`;try{const x=new URL(u);return ["http:","https:"].includes(x.protocol)?x.toString():""}catch{return""}}
export default function PublicProfilePage(){
 const params=useParams<{id:string}>(); const {user,token,isLoading}=useAuth(); const id=String(params?.id||"")
 const [person,setPerson]=useState<any>(); const [projects,setProjects]=useState<any[]>([]); const [connections,setConnections]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("")
 useEffect(()=>{if(!id)return;let active=true;(async()=>{try{const [p,pr]=await Promise.all([fetchUserById(id),fetchProjects()]);if(!active)return;setPerson(p?.user||p);setProjects((pr?.projects||[]).filter((x:any)=>String(x.owner?.id||x.owner?._id||x.owner)===id).slice(0,12));if(token&&String((user as AuthUserLike)?.id||(user as AuthUserLike)?._id)!==id){void recordProfileView(id,token).catch(()=>{});const c=await fetchConnections(token);if(active)setConnections(c?.connections||[])}}catch(e:any){if(active)setError(e?.message||"Unable to load profile")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[id,token,user])
 const relation=useMemo(()=>connections.find(c=>String(c.requester?._id||c.requester)===id||String(c.recipient?._id||c.recipient)===id),[connections,id])
 const connect=async()=>{if(!token)return;setBusy(true);try{await requestConnection(id,token);const c=await fetchConnections(token);setConnections(c?.connections||[])}catch(e:any){setError(e?.message||"Unable to send request")}finally{setBusy(false)}}
 if(isLoading||loading)return <div className="min-h-screen bg-background text-foreground grid place-items-center">Loading profile...</div>
 if(!person)return <div className="min-h-screen bg-background text-destructive grid place-items-center">{error||"Profile not found."}</div>
 const initials=`${person.firstName?.[0]||""}${person.lastName?.[0]||""}`.toUpperCase(); const own=String((user as AuthUserLike)?.id||(user as AuthUserLike)?._id)===id
 const links=[{label:"GitHub",icon:Github,url:safeUrl(person.socialLinks?.github)},{label:"LinkedIn",icon:Linkedin,url:safeUrl(person.socialLinks?.linkedin)},{label:"Twitter",icon:Twitter,url:safeUrl(person.socialLinks?.twitter)},{label:"Portfolio",icon:Globe,url:safeUrl(person.socialLinks?.website)}].filter(x=>x.url)
 return <div className="min-h-screen bg-background text-foreground"><nav className="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4"><Link href="/dashboard" className="flex items-center gap-2 text-xl font-bold"><Code2 className="text-primary"/>DevHeaven</Link><div className="flex items-center gap-2"><ThemeToggle/><Link href="/discovery"><Button variant="outline">Network</Button></Link>{own&&<Link href="/profile"><Button>Edit profile</Button></Link>}</div></div></nav>
 <main className="mx-auto max-w-5xl space-y-6 px-4 py-8"><Card><CardContent className="pt-6"><div className="flex flex-col items-center gap-6 md:flex-row md:items-start"><Avatar className="h-28 w-28"><AvatarImage src={assetUrl(person.profileImage)}/><AvatarFallback className="text-2xl">{initials}</AvatarFallback></Avatar><div className="flex-1 text-center md:text-left"><div className="flex flex-col gap-4 md:flex-row md:justify-between"><div><h1 className="text-3xl font-bold">{person.firstName} {person.lastName}</h1><p className="text-muted-foreground">@{person.username}</p></div>{!own&&token&&<div className="flex justify-center gap-2"><Button variant="outline" asChild><Link href={`/messages?user=${encodeURIComponent(id)}`}><MessageSquare className="mr-2 h-4 w-4"/>Message</Link></Button>{relation?.status==="accepted"?<Button variant="outline" disabled><UserCheck className="mr-2 h-4 w-4"/>Connected</Button>:relation?.status==="pending"?<Button variant="outline" disabled><Clock3 className="mr-2 h-4 w-4"/>Pending</Button>:<Button onClick={()=>void connect()} disabled={busy}><UserPlus className="mr-2 h-4 w-4"/>{busy?"Sending...":"Connect"}</Button>}</div>}</div><p className="mt-4 whitespace-pre-wrap text-muted-foreground">{person.bio||"This developer has not added a bio yet."}</p><div className="mt-4 flex flex-wrap gap-4 text-sm text-muted-foreground">{person.location&&<span className="flex items-center gap-1"><MapPin className="h-4 w-4"/>{person.location}</span>}{person.experience!=null&&<span className="flex items-center gap-1"><Briefcase className="h-4 w-4"/>{person.experience} years experience</span>}{person.createdAt&&<span className="flex items-center gap-1"><Calendar className="h-4 w-4"/>Joined {formatLocalDateTime(person.createdAt)}</span>}</div><div className="mt-4 flex flex-wrap gap-2">{(person.skills||[]).map((s:string)=><Badge key={s} variant="secondary">{s}</Badge>)}</div>{links.length>0&&<div className="mt-5 flex flex-wrap gap-3">{links.map(({label,icon:Icon,url})=><a key={label} href={url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm text-foreground hover:bg-muted"><Icon className="h-4 w-4"/>{label}</a>)}</div>}</div></div></CardContent></Card>
 {error&&<div className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<Card><CardHeader><CardTitle>Projects ({projects.length})</CardTitle></CardHeader><CardContent>{projects.length===0?<p className="text-sm text-muted-foreground">No public projects yet.</p>:<div className="grid gap-4 md:grid-cols-2">{projects.map(p=><div key={p.id||p._id} className="rounded-lg border border-border p-4"><h3 className="font-semibold">{p.title}</h3><p className="mt-2 line-clamp-3 text-sm text-muted-foreground">{p.description}</p><div className="mt-3 flex flex-wrap gap-1">{(p.techStack||[]).map((t:string)=><Badge key={t} variant="outline" className="text-xs">{t}</Badge>)}</div><div className="mt-4 flex gap-2">{p.githubUrl&&<Button size="sm" variant="outline" asChild><a href={p.githubUrl} target="_blank" rel="noopener noreferrer"><Github className="mr-1 h-4 w-4"/>Code</a></Button>}{p.liveUrl&&<Button size="sm" asChild><a href={p.liveUrl} target="_blank" rel="noopener noreferrer">Live demo</a></Button>}</div></div>)}</div>}</CardContent></Card></main></div>
}
